lang: "ko"
title: "log0"
description: ""

# Your site URL (for production)
url: "https://log-zero.github.io"
baseurl: ""

# Plugins (GitHub Pages supports only limited plugins)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Permalinks: /year/month/day/
permalink: /:year/:month/:day/

# Exclude these files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

kramdown:
  math_engine: null